apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  type: LoadBalancer
  selector:
    app: galera
---
apiVersion: v1
kind: Service
metadata:
  name: galera
  labels:
    app: galera
spec:
  clusterIP: None
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic
    - port: 4568
      name: incremental-state-transfer
  selector:
    app: galera
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  # These values must be base64 encoded.
  # echo -n 'sst' | base64
  # sst user:pass sst:sst
  # root-password: youshallnotpass
  sst-username: c3N0
  sst-password: c3N0
  root-password: eW91c2hhbGxub3RwYXNz
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: galera
spec:
  serviceName: galera
  replicas: 3
  selector:
    matchLabels:
      app: galera
  template:
    metadata:
      labels:
        app: galera
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - resources:
            limits:
              cpu: 1
          livenessProbe:
            exec:
              command: ["mysqladmin", "-u", "dummy", "ping"]
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["mysql", "-h", "127.0.0.1", "-u", "dummy", "-e", "SELECT 1"]
            initialDelaySeconds: 5
            timeoutSeconds: 1
          image: andygabby/pxc-57:v3
          imagePullPolicy: Always
          name: mysql
          ports:
            - containerPort: 3306
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          env:
            - name: WSREP_SST_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: sst-username
            - name: WSREP_SST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: sst-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root-password
